[tool.poetry]
name = "snake"
version = "0.1.0"
description = ""
authors = ["Lioris10 <lior@crosstech.co.il>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pygame = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
